### ISSUE TITLE
Disable mod name tooltip when Hwyla is installed (or provide config option)

### ISSUE THREAD

**Issue by sargunv** [CottonMC/MetaTips#1]
Hwyla provides the mod name too, so they get doubled up.

**Comment by LemmaEOF** [comment]
I'm actually not seeing where REI does this. Hm.

**Comment by sargunv** [comment]
Ah, maybe it's hwyla, let me double check

**Comment by sargunv** [comment]
Confirmed it's Hwyla, not REI

**Comment by LemmaEOF** [comment]
fixed, and a PR set into Hwyla to have support for the `c:` namespace.
