### ISSUE TITLE
that's craby dude

### ISSUE THREAD

**Issue by Yoghurt4C** [CottonMC/MetaTips#3]
unexpectedly, the client shuts down while trying to render any (probably) tooltip on 19w46b with the `1.1.6+1.14.4` version from CF 🙂 
https://pastebin.com/g1PBRtdk

**Comment by LemmaEOF** [comment]
Huh. It's calling `Tag.idToString` to format the int tag type as a string, but that apparently got nuked in a snapshot. I'll try to see if there's a good replacement.

**Comment by LemmaEOF** [comment]
fixed with 1.1.7+1.14.4, uploading to CF now
